NUM_TYPE_SHOES = 5

STOP_ROBOT = -2
NOTHING_IN_SIGHT = -1
SERGE_LOOK = 0
SHASHANK_ORBIT = 1
TOM_CIRCLE = 2
VARUN_FOLLOW = 3
VASILIS_EIGHT = 4

PATH_FINISHED = 1

POSE_ERROR_RADIUS = 0.07
POSE_ERROR_RADIUS_STOP = 0.03
ANGLE_ERROR_RADIUS = 0.3